# -*- coding: utf-8 -*-
"""Untitled78.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1baccF1G27WAFCKSA7hZvQRVt55h3_Qqx
"""

pip install streamlit

import streamlit as st
st.title("Plotly Visualizations!!!")